"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.utils.translation import ugettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9a)$n_*pll30e5_v(k2g6i^4tjfh@=q*xk)s4oxbyx^4o3^ae+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# TEMPLATE_DEBUG = DEBUG

ALLOWED_HOSTS = ['127.0.0.1']

SITE_ID = 1

# Настройка предусматривает отправку разработчикам сайта сообщений обо всех необработанных исключениях по электронной почте
ADMINS = (
    ("Михайло Поліщук", "mishaelitzem2@rambler.ru"),
)

EMAIL_HOST = 'smtp.gmail.com'                # Имя хоста используемое для отправки электронных писем. По умолчанию 'localhost'
EMAIL_HOST_USER = 'yourgmail@gmail.com'      # Имя пользователя используемое при подключении к SMTP серверу указанному в EMAIL_HOST
EMAIL_HOST_PASSWORD = 'yourpassword'         # Пароль для подключения к SMTP сервера, который указан в EMAIL_HOST
EMAIL_SUBJECT_PREFIX = '[Django]'            # Префикс добавляемый к теме электронного письма
EMAIL_PORT = 587                             # Порт, используемый при подключении к SMTP серверу указанному в EMAIL_HOST.
EMAIL_USE_TLS = True                         # Указывает использовать ли TLS (защищенное) соединение с SMTP сервером. По умолчанию использует 587 порт.
EMAIL_USE_SSL = False                        # Указывает использовать ли TLS (защищенное) соединение с SMTP сервером. По умолчанию использует 465 порт.
# Обратите внимание, EMAIL_USE_TLS/EMAIL_USE_SSL взаимоисключающие, только одна настройка может быть True.

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # other django apps
    'django.contrib.sites',
    'django.contrib.flatpages',
    # my apps
    'blog',
    'comment',
    'loginsys',
    'navigation',
    'languages',
)
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',               # add this line after the SessionMiddleware for translate
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # other MIDDLEWARE_CLASSES
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware'
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'blog/templates/../blog/templates/blog'),
                 os.path.join(BASE_DIR,
                              'navigation/templates/../navigation/templates/navigation'),
                 os.path.join(BASE_DIR,
                              'languages/templates/languages')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',                  # add this processor for translate
                'django.core.context_processors.csrf',
                ],
            },
        },
    ]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',   # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'django',                                     # Or path to database file if using sqlite3.
        'USER': 'postgres',
        'PASSWORD': '170986',
        'HOST': 'localhost',    # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': '',             # Set to empty string for default.
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
# 'ru-Ru'
# 'uk-Uk'
# 'en-En'

# default language  (it don`t work if MIDDLEWARE_CLASSES have 'django.middleware.locale.LocaleMiddleware'
#  and TEMPLATES have 'django.core.context_processors.i18n')

LANGUAGE_CODE = 'uk-Uk'

# list of languages
LANGUAGES = (
    ('en', _('English')),
    ('uk', _('Ukraine')),
    ('ru', _('Russia')),
)


# directory which will host po and mo files
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'blog', 'static', 'blog'),
    os.path.join(BASE_DIR, 'blog', 'static', 'upload'),
    os.path.join(BASE_DIR, 'loginsys', 'static', 'upload'),
    os.path.join(BASE_DIR, 'languages', 'static', 'languages/img'),
)

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'mysite/../../static_and_media', 'static_root')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'mysite/../../static_and_media', 'media_root')
