# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 10:05
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160922_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, height_field='width_field', help_text='Зображення до статті', null=True, upload_to=blog.models.upload_location, verbose_name='Картинки', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(blank='', unique='', verbose_name='Ім`я статті транслітом'),
        ),
    ]
